title: Forensics Conference Deadlines
description: Countdowns to forensics conference deadlines
author: Benedikt Lorch

domain: "https://btlorch.github.io/forensics-deadlines/"
baseurl: "/forensics-deadlines"

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: btlorch
github_repo: forensics-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']